image: flink
imageTag: latest
imagePullPolicy: Always

nodeSelector: {}

ingress:
  enabled: false
  annotations: {}
  host: <host>
  path: /
  tls:
    enabled: true

resources:
  jobmanager:
    limits:
      cpu: 1000m
      memory: 1280Mi
    requests:
      cpu: 1000m
      memory: 1280Mi
  taskmanager:
    limits:
      memory: 2048Mi
    requests:
      memory: 2048Mi

flink:
  jobmanager_heap_mb: 1024
  taskmanager_heap_mb: 1024
  num_taskmanagers: 2
  num_slots_per_taskmanager: 2

  ## Other config options for flink-conf.yaml
  config: |
    taskmanager.rpc.port: 6122
    queryable-state.proxy.ports: 6125
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    parallelism.default: 2